import {useState} from "react";
import {ArrowDownLeft,ArrowUpRight,Boxes,CircleDollarSign,FileBarChart,Receipt,ShoppingBasket,SlidersHorizontal,TriangleAlert,UserPlus,Users,WalletCards} from "lucide-react";
import {Area,AreaChart,Bar,BarChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {Link} from "react-router-dom";import {useTranslation} from "react-i18next";
import {useClients,useExpenses,useInventory,useLedger,usePurchases} from "../hooks";
import {money} from "../types";import {Badge,ChartCard,MobileDataCard,PageHeader,StatCard} from "../components/ui";

const day=(date:Date)=>date.toISOString().slice(0,10);
export default function Dashboard(){
 const {t}=useTranslation(),today=day(new Date());const [selectedDate,setSelectedDate]=useState(today);
 const clients=useClients().data||[],inventory=useInventory().data||[],purchases=usePurchases().data||[],ledger=useLedger().data||[],expenses=useExpenses().data||[];
 const selectedPurchases=purchases.filter(x=>x.purchase_date===selectedDate&&x.status==="completed");
 const selectedRecoveries=ledger.filter(x=>x.entry_date===selectedDate&&x.entry_type==="credit");
 const selectedExpenses=expenses.filter(x=>x.expense_date===selectedDate);
 const purchaseValue=selectedPurchases.reduce((s,x)=>s+Number(x.grand_total),0);
 const recoveryValue=selectedRecoveries.reduce((s,x)=>s+Math.abs(Number(x.amount)),0);
 const expenseValue=selectedExpenses.reduce((s,x)=>s+Number(x.amount),0);
 const outstanding=clients.reduce((s,c)=>s+Number(c.balance||0),0),invValue=inventory.reduce((s,x)=>s+Number(x.current_stock)*Number(x.purchase_rate),0),low=inventory.filter(x=>Number(x.current_stock)<=Number(x.minimum_stock));
 const anchor=new Date(`${selectedDate}T12:00:00`);const range=Array.from({length:7},(_,i)=>{const d=new Date(anchor);d.setDate(d.getDate()-6+i);return day(d)});
 const trend=range.map(date=>({label:new Date(`${date}T12:00:00`).toLocaleDateString("en-PK",{weekday:"short"}),purchase:purchases.filter(x=>x.purchase_date===date&&x.status==="completed").reduce((s,x)=>s+Number(x.grand_total),0),recovery:ledger.filter(x=>x.entry_date===date&&x.entry_type==="credit").reduce((s,x)=>s+Math.abs(Number(x.amount)),0),expense:expenses.filter(x=>x.expense_date===date).reduce((s,x)=>s+Number(x.amount),0)}));
 const dateLabel=selectedDate===today?t("liveTransactions"):new Date(`${selectedDate}T12:00:00`).toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"});
 const stats=[{title:t("todayPurchase"),value:money(purchaseValue),icon:ShoppingBasket,tone:"green" as const,detail:dateLabel},{title:t("todayRecovery"),value:money(recoveryValue),icon:ArrowDownLeft,tone:"green" as const,detail:dateLabel},{title:t("todayExpenses"),value:money(expenseValue),icon:Receipt,tone:"amber" as const,detail:dateLabel},{title:t("cashInHand"),value:money(recoveryValue-expenseValue),icon:CircleDollarSign,tone:"blue" as const,detail:dateLabel},{title:t("totalOutstanding"),value:money(outstanding),icon:WalletCards,tone:"red" as const,detail:t("clientReceivables")},{title:t("totalClients"),value:clients.filter(x=>x.is_active).length,icon:Users,tone:"purple" as const,detail:t("activeAccounts")},{title:t("inventoryValue"),value:money(invValue),icon:Boxes,tone:"green" as const,detail:t("currentValuation")},{title:t("lowStockAlerts"),value:low.length,icon:TriangleAlert,tone:"amber" as const,detail:t("needsAttention")}];
 return <div className="space-y-4">
  <div className="card flex flex-col gap-3 bg-[var(--primary-soft)] p-4 md:flex-row md:items-center md:justify-between md:border-0 md:bg-transparent md:p-0 md:shadow-none"><PageHeader title={`${t("welcome")}, ${t("administrator")}`} description={t("dashboardDesc")}/><input aria-label="Dashboard date" type="date" value={selectedDate} onChange={e=>setSelectedDate(e.target.value)} className="field w-full md:w-auto"/></div>
  <div className="metric-grid grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{stats.map(x=><StatCard key={x.title} {...x}/>)}</div>
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div className="xl:col-span-2"><ChartCard title={t("purchaseVsRecovery")} subtitle={`${t("lastSevenDays")} · ${dateLabel}`}><Chart type="area" data={trend}/></ChartCard></div><ChartCard title={t("expenseTrend")} subtitle={dateLabel}><Chart type="bar" data={trend}/></ChartCard><ChartCard title={t("cashFlow")} subtitle={dateLabel}><Chart type="line" data={trend}/></ChartCard></div>
  <section className="card overflow-hidden"><div className="flex items-center justify-between border-b bg-[var(--surface-secondary)] px-4 py-3"><div><h2 className="text-sm font-bold">Quick actions</h2><p className="mt-0.5 text-[11px] text-[var(--text-muted)]">Create entries and open daily workflows</p></div><span className="hidden rounded-full bg-[var(--primary-soft)] px-2.5 py-1 text-[10px] font-semibold text-[var(--primary)] sm:inline">6 shortcuts</span></div><div className="grid grid-cols-2 gap-2 p-3 sm:grid-cols-3 xl:grid-cols-6"><Action to="/purchases" icon={ShoppingBasket} title={t("newPurchase")} detail="Create produce lot" tone="green"/><Action to="/ledger" icon={ArrowDownLeft} title={t("addPayment")} detail="Record client cash" tone="blue"/><Action to="/clients" icon={UserPlus} title={t("addClient")} detail="Open new account" tone="purple"/><Action to="/expenses" icon={Receipt} title={t("addExpense")} detail="Record operating cost" tone="amber"/><Action to="/inventory" icon={SlidersHorizontal} title={t("stockAdjustment")} detail="Correct stock level" tone="green"/><Action to="/reports" icon={FileBarChart} title={t("viewReports")} detail="Analyze performance" tone="blue"/></div></section>
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Activity title={t("recentPurchases")} to="/purchases" rows={selectedPurchases.map(x=>({title:x.client_name,sub:x.purchase_date,amount:money(x.grand_total),status:<Badge tone="green">{x.status}</Badge>}))}/><Activity title={t("recentRecoveries")} to="/ledger" rows={selectedRecoveries.map(x=>({title:x.client_name,sub:x.entry_date,amount:money(x.amount),status:<Badge tone="green">Recovery</Badge>}))}/><Activity title={t("recentExpenses")} to="/expenses" rows={selectedExpenses.map(x=>({title:x.title,sub:x.expense_date,amount:money(x.amount),status:<Badge tone="amber">{x.category}</Badge>}))}/><Activity title={t("alertsNotifications")} to="/inventory" rows={low.map(x=>({title:x.name,sub:`${x.current_stock} ${x.unit} remaining`,status:<Badge tone="amber">Low stock</Badge>}))}/></div>
 </div>
}
function Chart({type,data}:{type:"area"|"bar"|"line";data:{label:string;purchase:number;recovery:number;expense:number}[]}){return <div className="h-56"><ResponsiveContainer width="100%" height="100%">{type==="area"?<AreaChart data={data}><CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={(v:number)=>money(v)}/><Area dataKey="purchase" stroke="var(--primary)" fill="var(--primary-soft)"/><Line dataKey="recovery" stroke="var(--info)"/></AreaChart>:type==="bar"?<BarChart data={data}><XAxis dataKey="label" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={(v:number)=>money(v)}/><Bar dataKey="expense" fill="var(--warning)" radius={[4,4,0,0]}/></BarChart>:<LineChart data={data.map(x=>({...x,cash:x.recovery-x.expense}))}><XAxis dataKey="label" axisLine={false} tickLine={false}/><YAxis hide/><Tooltip formatter={(v:number)=>money(v)}/><Line dataKey="cash" stroke="var(--info)" strokeWidth={2.5}/></LineChart>}</ResponsiveContainer></div>}
function Activity({title,to,rows}:{title:string;to:string;rows:{title:string;sub:string;amount?:string;status?:React.ReactNode}[]}){return <section className="card overflow-hidden"><div className="flex items-center justify-between border-b px-4 py-3"><h2 className="text-sm font-bold">{title}</h2><Link className="text-[11px] font-semibold text-[var(--primary)]" to={to}>View all</Link></div><div className="grid gap-2 p-3">{rows.length?rows.slice(0,4).map((r,i)=><MobileDataCard key={i} title={r.title} subtitle={r.sub} amount={r.amount} status={r.status}/>):<p className="py-7 text-center text-xs text-[var(--text-muted)]">No activity for this date</p>}</div></section>}
function Action({to,icon:Icon,title,detail,tone}:{to:string;icon:React.ElementType;title:string;detail:string;tone:"green"|"blue"|"purple"|"amber"}){const colors={green:"bg-[var(--primary-soft)] text-[var(--primary)]",blue:"bg-[var(--info-soft)] text-[var(--info)]",purple:"bg-[var(--purple-soft)] text-[var(--purple)]",amber:"bg-[var(--warning-soft)] text-[var(--warning)]"};return <Link to={to} className="group flex min-h-[88px] items-center gap-3 rounded-[10px] border bg-[var(--surface)] p-3 hover:border-[var(--border-strong)] hover:bg-[var(--surface-secondary)] hover:shadow-[0_4px_14px_rgba(15,35,25,.08)]"><span className={`grid size-10 shrink-0 place-items-center rounded-[10px] ${colors[tone]}`}><Icon className="size-[19px]"/></span><span className="min-w-0 flex-1"><b className="block truncate text-xs">{title}</b><small className="mt-1 block truncate text-[10px] text-[var(--text-muted)]">{detail}</small></span><ArrowUpRight className="size-3.5 shrink-0 text-[var(--text-muted)] transition-transform duration-150 group-hover:-translate-y-0.5 group-hover:translate-x-0.5 rtl:rotate-[-90deg]"/></Link>}
