import {useMemo,useState} from "react";import {useMutation,useQueryClient} from "@tanstack/react-query";import {CalendarDays,Check,ChevronDown,Loader2,Pencil,Plus,Receipt,Trash2,Wallet} from "lucide-react";
import api,{errorMessage} from "../api";import {useExpenses} from "../hooks";import {Expense,money} from "../types";import {Badge,ConfirmDialog,DateRangeFilter,EmptyState,ErrorState,FormModal,MobileDataCard,PageHeader,SearchInput,StatCard} from "../components/ui";import {toast} from "../components/Toast";
const blank={category:"General",title:"",amount:"",expense_date:new Date().toISOString().slice(0,10),paid_to:"",payment_method:"Cash",notes:""};
const categories=["General","Labour / Wages","Loading / Unloading","Transport / Freight","Market Fee","Commission","Rent","Electricity / Utilities","Fuel","Repairs / Maintenance","Packaging","Food / Refreshment","Office Supplies","Salaries","Taxes / Government Fee","Cleaning","Security","Bank Charges","Miscellaneous"];
export default function Expenses(){
 const qc=useQueryClient(),q=useExpenses(),data=q.data||[];const [search,setSearch]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[modal,setModal]=useState(false),[editing,setEditing]=useState<Expense|null>(null),[del,setDel]=useState<Expense|null>(null),[f,setF]=useState(blank);
 const filtered=useMemo(()=>data.filter(x=>(x.title+x.category+x.paid_to).toLowerCase().includes(search.toLowerCase())&&(!from||x.expense_date>=from)&&(!to||x.expense_date<=to)),[data,search,from,to]);const today=new Date().toISOString().slice(0,10),month=today.slice(0,7);
 const save=useMutation({mutationFn:()=>editing?api.patch(`/expenses/${editing.id}/`,f):api.post("/expenses/",f),onSuccess:()=>{void qc.invalidateQueries({queryKey:["expenses"]});setModal(false);setEditing(null);setF(blank);toast(editing?"Expense updated":"Expense added")},onError:e=>toast(errorMessage(e),"error")});
 const remove=useMutation({mutationFn:(id:number)=>api.delete(`/expenses/${id}/`),onSuccess:()=>{void qc.invalidateQueries({queryKey:["expenses"]});setDel(null);toast("Expense deleted")},onError:e=>toast(errorMessage(e),"error")});const edit=(x:Expense)=>{setEditing(x);setF({...blank,...x});setModal(true)};if(q.isError)return <ErrorState message={errorMessage(q.error)} onRetry={()=>void q.refetch()}/>;
 return <div className="space-y-4"><PageHeader title="Expenses" description="Record operating costs and payment methods."><button className="btn-primary" onClick={()=>{setEditing(null);setF(blank);setModal(true)}}><Plus/>Add expense</button></PageHeader>
  <div className="metric-grid grid gap-3 sm:grid-cols-3"><StatCard title="Today" value={money(data.filter(x=>x.expense_date===today).reduce((s,x)=>s+Number(x.amount),0))} icon={Receipt} tone="amber"/><StatCard title="This month" value={money(data.filter(x=>x.expense_date.startsWith(month)).reduce((s,x)=>s+Number(x.amount),0))} icon={CalendarDays} tone="amber"/><StatCard title="All recorded" value={money(data.reduce((s,x)=>s+Number(x.amount),0))} icon={Wallet} tone="amber"/></div>
  <div className="card grid gap-2 p-3 lg:grid-cols-[1fr_auto]"><SearchInput value={search} onChange={setSearch} placeholder="Search expenses..."/><DateRangeFilter from={from} to={to} onFrom={setFrom} onTo={setTo}/></div>
  <section className="table-wrap"><div className="desktop-table overflow-x-auto">{filtered.length?<table className="data-table"><thead><tr><th>Date</th><th>Expense</th><th>Category</th><th>Paid to</th><th>Method</th><th className="numeric">Amount</th><th>Actions</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td>{x.expense_date}</td><td className="font-semibold">{x.title}</td><td><Badge tone="amber">{x.category}</Badge></td><td>{x.paid_to||"—"}</td><td>{x.payment_method||"—"}</td><td className="numeric font-semibold">{money(x.amount)}</td><td><Actions x={x} edit={edit} del={setDel}/></td></tr>)}</tbody></table>:<EmptyState/>}</div><div className="mobile-cards gap-2 p-3">{filtered.map(x=><MobileDataCard key={x.id} title={x.title} subtitle={`${x.expense_date} · ${x.category}`} amount={money(x.amount)} status={<Badge tone="amber">{x.payment_method}</Badge>} actions={<Actions x={x} edit={edit} del={setDel}/>}/>)}</div></section>
  <FormModal open={modal} onClose={()=>setModal(false)} title={editing?"Edit expense":"Add expense"} variant="full"><form className="grid gap-4 p-5 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();save.mutate()}}><Field label="Title"><input required className="field" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></Field><Field label="Category"><CategoryInput value={f.category} onChange={category=>setF({...f,category})}/></Field><Field label="Amount (PKR)"><input required min="0.01" step="0.01" type="number" className="field" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></Field><Field label="Date"><input required type="date" className="field" value={f.expense_date} onChange={e=>setF({...f,expense_date:e.target.value})}/></Field><Field label="Paid to"><input className="field" value={f.paid_to} onChange={e=>setF({...f,paid_to:e.target.value})}/></Field><Field label="Payment method"><select className="field" value={f.payment_method} onChange={e=>setF({...f,payment_method:e.target.value})}><option>Cash</option><option>Bank transfer</option><option>Cheque</option><option>Mobile wallet</option></select></Field><label className="sm:col-span-2"><span className="label">Notes</span><textarea className="field min-h-24 p-3" value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label><div className="sticky bottom-0 col-span-full flex justify-end gap-2 border-t bg-[var(--surface)] py-3"><button type="button" className="btn-secondary" onClick={()=>setModal(false)}>Cancel</button><button className="btn-primary" disabled={save.isPending}>{save.isPending?<Loader2 className="size-4 animate-spin"/>:"Save expense"}</button></div></form></FormModal><ConfirmDialog open={!!del} onClose={()=>setDel(null)} onConfirm={()=>del&&remove.mutate(del.id)} loading={remove.isPending}/>
 </div>
}
function CategoryInput({value,onChange}:{value:string;onChange:(v:string)=>void}){const [open,setOpen]=useState(false),matches=categories.filter(x=>x.toLowerCase().includes(value.toLowerCase()));return <div className="relative"><div className="relative"><input required role="combobox" aria-expanded={open} className="field pe-10" value={value} placeholder="Select or type expense category" onFocus={()=>setOpen(true)} onClick={()=>setOpen(true)} onBlur={()=>setTimeout(()=>setOpen(false),150)} onChange={e=>{onChange(e.target.value);setOpen(true)}}/><button type="button" className="absolute end-0 top-0 grid size-[42px] place-items-center text-[var(--text-muted)]" onMouseDown={e=>e.preventDefault()} onClick={()=>setOpen(x=>!x)}><ChevronDown className={`size-4 ${open?"rotate-180":""}`}/></button></div>{open&&<div className="absolute inset-x-0 top-[46px] z-40 max-h-60 overflow-y-auto rounded-[10px] border bg-[var(--surface)] p-1.5 shadow-[0_12px_30px_rgba(15,35,25,.12)]">{matches.length?matches.map(x=><button key={x} type="button" className="flex min-h-10 w-full items-center rounded-lg px-3 text-start text-sm hover:bg-[var(--warning-soft)]" onMouseDown={e=>e.preventDefault()} onClick={()=>{onChange(x);setOpen(false)}}><span className="flex-1">{x}</span>{value===x&&<Check className="size-4 text-[var(--warning)]"/>}</button>):<p className="p-3 text-xs text-[var(--text-muted)]">No matching category. Continue typing to use your custom category.</p>}</div>}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="label">{label}</span>{children}</label>}function Actions({x,edit,del}:{x:Expense;edit:(x:Expense)=>void;del:(x:Expense)=>void}){return <div className="flex"><button className="btn-ghost px-2" aria-label="Edit expense" onClick={()=>edit(x)}><Pencil/></button><button className="btn-ghost px-2 text-[var(--danger)]" aria-label="Delete expense" onClick={()=>del(x)}><Trash2/></button></div>}
