import {useMemo,useState} from "react";import {useMutation,useQueryClient} from "@tanstack/react-query";import {CalendarDays,Check,ChevronDown,Loader2,Pencil,Plus,Receipt,Trash2,Wallet} from "lucide-react";
import api,{errorMessage} from "../api";import {useExpenses} from "../hooks";import {Expense,money} from "../types";import {Badge,ConfirmDialog,DateNavigator,EmptyState,ErrorState,FormModal,MobileDataCard,ModuleHeader,SearchInput,StatCard} from "../components/ui";import {toast} from "../components/Toast";
const blank={category:"General",title:"",amount:"",expense_date:new Date().toISOString().slice(0,10),paid_to:"",payment_method:"Cash",notes:""};
const todayDate=new Date().toISOString().slice(0,10);
const PageHeader=({title,description,children}:{title:string;description?:string;children?:React.ReactNode})=><ModuleHeader title={title} description={description} icon={Receipt}>{children}</ModuleHeader>;
const categories=["General","Labour / Wages","Loading / Unloading","Transport / Freight","Market Fee","Commission","Rent","Electricity / Utilities","Fuel","Repairs / Maintenance","Packaging","Food / Refreshment","Office Supplies","Salaries","Taxes / Government Fee","Cleaning","Security","Bank Charges","Miscellaneous"];
export default function Expenses(){
 const qc=useQueryClient(),q=useExpenses(),data=q.data||[];const [search,setSearch]=useState(""),[from,setFrom]=useState(todayDate),[to,setTo]=useState(todayDate),[modal,setModal]=useState(false),[editing,setEditing]=useState<Expense|null>(null),[del,setDel]=useState<Expense|null>(null),[f,setF]=useState(blank);
 const filtered=useMemo(()=>data.filter(x=>(x.title+x.category+x.paid_to).toLowerCase().includes(search.toLowerCase())&&(!from||x.expense_date>=from)&&(!to||x.expense_date<=to)),[data,search,from,to]);const today=new Date().toISOString().slice(0,10),month=today.slice(0,7);const selectedDayTotal=data.filter(x=>x.expense_date===from).reduce((s,x)=>s+Number(x.amount),0);const selectedDayLabel=from===today?"Today":new Date(`${from}T00:00:00`).toLocaleDateString("en-PK",{day:"numeric",month:"short",year:"numeric"});
 const save=useMutation({mutationFn:()=>editing?api.patch(`/expenses/${editing.id}/`,f):api.post("/expenses/",f),onSuccess:()=>{void qc.invalidateQueries({queryKey:["expenses"]});setModal(false);setEditing(null);setF(blank);toast(editing?"Expense updated":"Expense added")},onError:e=>toast(errorMessage(e),"error")});
 const remove=useMutation({mutationFn:(id:number)=>api.delete(`/expenses/${id}/`),onSuccess:()=>{void qc.invalidateQueries({queryKey:["expenses"]});setDel(null);toast("Expense deleted")},onError:e=>toast(errorMessage(e),"error")});const edit=(x:Expense)=>{setEditing(x);setF({...blank,...x});setModal(true)};if(q.isError)return <ErrorState message={errorMessage(q.error)} onRetry={()=>void q.refetch()}/>;
 return <div className="space-y-4"><PageHeader title="Expenses" description="Record operating costs and payment methods."><button className="btn-primary" onClick={()=>{setEditing(null);setF(blank);setModal(true)}}><Plus/>Add expense</button></PageHeader>
  <div className="metric-grid grid gap-3 sm:grid-cols-3"><StatCard title={selectedDayLabel} value={money(selectedDayTotal)} icon={Receipt} tone="amber"/><StatCard title="This month" value={money(data.filter(x=>x.expense_date.startsWith(month)).reduce((s,x)=>s+Number(x.amount),0))} icon={CalendarDays} tone="amber"/><StatCard title="All recorded" value={money(data.reduce((s,x)=>s+Number(x.amount),0))} icon={Wallet} tone="amber"/></div>
  <div className="card grid gap-2 p-3 lg:grid-cols-[1fr_auto]"><SearchInput value={search} onChange={setSearch} placeholder="Search expenses..."/><DateNavigator value={from} onChange={value=>{setFrom(value);setTo(value)}} label="Expense date" className="w-full lg:w-[270px]"/></div>
  <section className="table-wrap"><div className="desktop-table overflow-x-auto">{filtered.length?<table className="data-table"><thead><tr><th>Expense</th><th>Date</th><th>Category</th><th>Paid to</th><th>Method</th><th className="numeric">Amount</th><th>Actions</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><ExpenseIdentity expense={x}/></td><td>{x.expense_date}</td><td><Badge tone="amber">{x.category}</Badge></td><td>{x.paid_to||"—"}</td><td>{x.payment_method||"—"}</td><td className="numeric font-semibold">{money(x.amount)}</td><td><Actions x={x} edit={edit} del={setDel}/></td></tr>)}</tbody></table>:<EmptyState title="No expenses for this day" description="Choose another date or add today’s first expense."/>}</div><div className="mobile-cards gap-2 p-3">{filtered.map(x=><MobileDataCard key={x.id} title={`${expenseMeta(x.category).emoji} ${x.title}`} subtitle={`${x.expense_date} · ${x.category}`} amount={money(x.amount)} status={<Badge tone="amber">{x.payment_method}</Badge>} actions={<Actions x={x} edit={edit} del={setDel}/>}/>)}</div></section>
  <FormModal open={modal} onClose={()=>setModal(false)} title={editing?"Edit expense":"Add expense"} variant="full"><form className="grid gap-4 p-5 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();save.mutate()}}><Field label="Title"><input required className="field" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/></Field><Field label="Category"><CategoryInput value={f.category} onChange={category=>setF({...f,category})}/></Field><Field label="Amount (PKR)"><input required min="0.01" step="0.01" type="number" className="field" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/></Field><Field label="Date"><DateNavigator required value={f.expense_date} onChange={expense_date=>setF({...f,expense_date})}/></Field><Field label="Paid to"><input className="field" value={f.paid_to} onChange={e=>setF({...f,paid_to:e.target.value})}/></Field><Field label="Payment method"><select className="field" value={f.payment_method} onChange={e=>setF({...f,payment_method:e.target.value})}><option>Cash</option><option>Bank transfer</option><option>Cheque</option><option>Mobile wallet</option></select></Field><label className="sm:col-span-2"><span className="label">Notes</span><textarea className="field min-h-24 p-3" value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label><div className="sticky bottom-0 col-span-full flex justify-end gap-2 border-t bg-[var(--surface)] py-3"><button type="button" className="btn-secondary" onClick={()=>setModal(false)}>Cancel</button><button className="btn-primary" disabled={save.isPending}>{save.isPending?<Loader2 className="size-4 animate-spin"/>:"Save expense"}</button></div></form></FormModal><ConfirmDialog open={!!del} onClose={()=>setDel(null)} onConfirm={()=>del&&remove.mutate(del.id)} loading={remove.isPending}/>
 </div>
}
function CategoryInput({value,onChange}:{value:string;onChange:(v:string)=>void}){const [open,setOpen]=useState(false),matches=categories.filter(x=>x.toLowerCase().includes(value.toLowerCase()));return <div className="relative"><div className="relative"><input required role="combobox" aria-expanded={open} className="field pe-10" value={value} placeholder="Select or type expense category" onFocus={()=>setOpen(true)} onClick={()=>setOpen(true)} onBlur={()=>setTimeout(()=>setOpen(false),150)} onChange={e=>{onChange(e.target.value);setOpen(true)}}/><button type="button" className="absolute end-0 top-0 grid size-[42px] place-items-center text-[var(--text-muted)]" onMouseDown={e=>e.preventDefault()} onClick={()=>setOpen(x=>!x)}><ChevronDown className={`size-4 ${open?"rotate-180":""}`}/></button></div>{open&&<div className="absolute inset-x-0 top-[46px] z-40 max-h-60 overflow-y-auto rounded-[10px] border bg-[var(--surface)] p-1.5 shadow-[0_12px_30px_rgba(15,35,25,.12)]">{matches.length?matches.map(x=><button key={x} type="button" className="flex min-h-10 w-full items-center rounded-lg px-3 text-start text-sm hover:bg-[var(--warning-soft)]" onMouseDown={e=>e.preventDefault()} onClick={()=>{onChange(x);setOpen(false)}}><span className="flex-1">{x}</span>{value===x&&<Check className="size-4 text-[var(--warning)]"/>}</button>):<p className="p-3 text-xs text-[var(--text-muted)]">No matching category. Continue typing to use your custom category.</p>}</div>}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="label">{label}</span>{children}</label>}function Actions({x,edit,del}:{x:Expense;edit:(x:Expense)=>void;del:(x:Expense)=>void}){return <div className="flex"><button className="btn-ghost px-2" aria-label="Edit expense" onClick={()=>edit(x)}><Pencil/></button><button className="btn-ghost px-2 text-[var(--danger)]" aria-label="Delete expense" onClick={()=>del(x)}><Trash2/></button></div>}
function expenseMeta(category:string){const c=category.toLowerCase();if(c.includes("transport")||c.includes("fuel"))return{emoji:"🚚",color:"bg-blue-100"};if(c.includes("labour")||c.includes("salary")||c.includes("wage"))return{emoji:"👷",color:"bg-amber-100"};if(c.includes("pack"))return{emoji:"📦",color:"bg-violet-100"};if(c.includes("market")||c.includes("tax")||c.includes("fee"))return{emoji:"🧾",color:"bg-rose-100"};if(c.includes("repair")||c.includes("maintenance"))return{emoji:"🔧",color:"bg-slate-100"};if(c.includes("electric")||c.includes("utilit"))return{emoji:"⚡",color:"bg-yellow-100"};if(c.includes("office"))return{emoji:"🗂️",color:"bg-cyan-100"};if(c.includes("food")||c.includes("refresh"))return{emoji:"☕",color:"bg-orange-100"};return{emoji:"💸",color:"bg-emerald-100"}}
function ExpenseIdentity({expense}:{expense:Expense}){const meta=expenseMeta(expense.category);return <div className="flex items-center gap-3"><span className={`grid size-10 shrink-0 place-items-center rounded-xl text-xl ring-1 ring-black/5 ${meta.color}`}>{meta.emoji}</span><div><b className="text-sm text-[var(--text-primary)]">{expense.title}</b><small className="mt-0.5 block text-[var(--text-muted)]">{expense.paid_to||expense.category}</small></div></div>}
