import {useMemo,useState} from "react";import {useMutation,useQueryClient} from "@tanstack/react-query";import {BookOpenCheck,CalendarDays,ChevronLeft,ChevronRight,Loader2,Search,Users} from "lucide-react";
import api,{errorMessage} from "../api";import {useClients,useLedger,usePurchases} from "../hooks";import {Client,money} from "../types";import {Badge,EmptyState,ErrorState,ExportButtons,MobileDataCard} from "../components/ui";import {toast} from "../components/Toast";import {useTranslation} from "react-i18next";
type DailyRow={client:Client;previous:number;purchase:number;paid:number;remaining:number};
export default function Ledger(){
 const {t,i18n}=useTranslation();
 const qc=useQueryClient(),ledgerQ=useLedger(),clientsQ=useClients(),purchasesQ=usePurchases();const ledger=ledgerQ.data||[],clients=clientsQ.data||[],purchases=purchasesQ.data||[];
 const [date,setDate]=useState(new Date().toISOString().slice(0,10)),[search,setSearch]=useState(""),[payments,setPayments]=useState<Record<number,string>>({});
 const rows=useMemo<DailyRow[]>(()=>clients.filter(c=>c.is_active&&(c.name+c.phone).toLowerCase().includes(search.toLowerCase())).map(client=>{const previous=Number(client.opening_balance)+ledger.filter(x=>x.client===client.id&&x.entry_date<date).reduce((s,x)=>s+Number(x.amount),0);const purchase=purchases.filter(x=>x.client===client.id&&x.purchase_date===date&&x.status==="completed").reduce((s,x)=>s+Number(x.grand_total),0);const paid=ledger.filter(x=>x.client===client.id&&x.entry_date===date&&x.entry_type==="credit").reduce((s,x)=>s+Math.abs(Number(x.amount)),0);return {client,previous,purchase,paid,remaining:previous+purchase-paid}}),[clients,ledger,purchases,date,search]);
 const totals=rows.reduce((a,x)=>({previous:a.previous+x.previous,purchase:a.purchase+x.purchase,paid:a.paid+x.paid,remaining:a.remaining+x.remaining}),{previous:0,purchase:0,paid:0,remaining:0});
 const add=useMutation({mutationFn:({client,amount}:{client:number;amount:number})=>api.post("/ledger/",{client,entry_type:"credit",amount:-Math.abs(amount),entry_date:date,description:`Recovery payment on ${date}`}),onSuccess:(_,v)=>{setPayments(x=>({...x,[v.client]:""}));void qc.invalidateQueries({queryKey:["ledger"]});void qc.invalidateQueries({queryKey:["clients"]});void qc.invalidateQueries({queryKey:["dashboard"]});toast("Recovery payment added")},onError:e=>toast(errorMessage(e),"error")});
 const pay=(row:DailyRow)=>{const amount=Number(payments[row.client.id]);if(!amount||amount<=0)return toast("Enter a valid payment amount","error");if(amount>Math.max(row.remaining,0))return toast(`Payment cannot exceed ${money(row.remaining)}`,"error");add.mutate({client:row.client.id,amount})};
 const shiftDate=(amount:number)=>{const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+amount);setDate(d.toISOString().slice(0,10))};
 if(ledgerQ.isError||clientsQ.isError||purchasesQ.isError)return <ErrorState message={errorMessage(ledgerQ.error||clientsQ.error||purchasesQ.error)} onRetry={()=>{void ledgerQ.refetch();void clientsQ.refetch();void purchasesQ.refetch()}}/>;
 return <div className="space-y-4"><section className="card overflow-hidden"><div className="flex flex-col gap-4 bg-[var(--sidebar)] p-5 text-white sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-white/12 ring-1 ring-white/15"><BookOpenCheck className="size-6"/></span><div><h1 className="text-xl font-bold">Recovery Book</h1><p className="mt-1 text-xs text-green-100">Daily buyer purchases, collections and outstanding balances</p></div></div><ExportButtons filename={`recovery-${date}`} rows={rows.map(x=>({name:x.client.name,previous_debit:x.previous,today_purchase:x.purchase,paid:x.paid,remaining:x.remaining}))}/></div><div className="grid gap-3 p-4 lg:grid-cols-[auto_minmax(260px,1fr)_auto]"><div><span className="label">Business date</span><div className="flex rounded-[10px] border bg-[var(--surface)]"><button aria-label="Previous day" className="grid size-[42px] place-items-center border-e hover:bg-[var(--surface-muted)]" onClick={()=>shiftDate(-1)}><ChevronLeft className="size-4 rtl:rotate-180"/></button><div className="relative"><CalendarDays className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-[var(--primary)]"/><input className="h-[42px] w-[170px] bg-transparent ps-9 pe-2 text-sm font-semibold outline-none" type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><button aria-label="Next day" className="grid size-[42px] place-items-center border-s hover:bg-[var(--surface-muted)]" onClick={()=>shiftDate(1)}><ChevronRight className="size-4 rtl:rotate-180"/></button></div></div><label><span className="label">Find buyer</span><div className="relative"><Search className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-[var(--text-muted)]"/><input className="field ps-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by buyer name or phone..."/>{search&&<button type="button" className="absolute end-2 top-1/2 -translate-y-1/2 rounded-md px-2 py-1 text-[10px] font-semibold text-[var(--primary)] hover:bg-[var(--primary-soft)]" onClick={()=>setSearch("")}>Clear</button>}</div></label><div className="flex items-end"><div className="flex h-[42px] items-center gap-2 rounded-[10px] bg-[var(--primary-soft)] px-3 text-xs font-semibold text-[var(--primary)]"><Users className="size-4"/>{rows.length} buyers</div></div></div><div className="grid grid-cols-2 border-t bg-[var(--surface-secondary)] sm:grid-cols-4"><Summary label="Previous debit" value={money(totals.previous)} tone="danger"/><Summary label="Today’s purchase" value={money(totals.purchase)} tone="primary"/><Summary label="Collected" value={money(totals.paid)} tone="info"/><Summary label="Remaining" value={money(totals.remaining)} tone={totals.remaining>0?"danger":"success"}/></div></section>
  <section className="table-wrap"><div className="border-b px-4 py-3"><h2 className="text-sm font-bold">Buyer Recovery — {new Date(`${date}T12:00:00`).toLocaleDateString("en-PK",{day:"numeric",month:"long",year:"numeric"})}</h2><p className="mt-0.5 text-[11px] text-[var(--text-muted)]">Use Full to fill the complete remaining balance, then select Add.</p></div><div className="desktop-table overflow-x-auto">{rows.length?<table className="data-table min-w-[980px]"><thead><tr className="bg-[var(--sidebar)]"><th className="!bg-[var(--sidebar)] !text-white">Name</th><th className="numeric !bg-[var(--sidebar)] !text-white">Debit (Previous)</th><th className="numeric !bg-[var(--sidebar)] !text-white">Today’s Purchase</th><th className="numeric !bg-[var(--sidebar)] !text-white">Credit / Paid</th><th className="numeric !bg-[var(--sidebar)] !text-white">Remaining</th><th className="!bg-[var(--sidebar)] !text-white">Add Payment</th></tr></thead><tbody>{rows.map(row=><tr key={row.client.id}><td><b>{row.client.name}</b><small className="block text-[var(--text-muted)]">{row.client.phone||"No phone"}</small></td><td className="numeric">{money(row.previous)}</td><td className="numeric font-semibold">{money(row.purchase)}</td><td className="numeric text-[var(--info)]">{money(row.paid)}</td><td className={`numeric font-bold ${row.remaining>0?"text-[var(--danger)]":"text-[var(--success)]"}`}>{money(row.remaining)} {row.remaining<=0&&<Badge tone="green">Settled</Badge>}</td><td><Payment row={row} value={payments[row.client.id]||""} setValue={v=>setPayments(x=>({...x,[row.client.id]:v}))} full={()=>setPayments(x=>({...x,[row.client.id]:String(Math.max(row.remaining,0))}))} add={()=>pay(row)} loading={add.isPending&&add.variables?.client===row.client.id}/></td></tr>)}</tbody><tfoot><tr className="bg-[var(--surface-muted)] font-bold"><td>TOTAL</td><td className="numeric">{money(totals.previous)}</td><td className="numeric">{money(totals.purchase)}</td><td className="numeric">{money(totals.paid)}</td><td className="numeric">{money(totals.remaining)}</td><td/></tr></tfoot></table>:<EmptyState title="No buyer found" description="Change the search text or add a buyer from Clients."/>}</div>
   <div className="mobile-cards gap-3 p-3">{rows.map(row=><div key={row.client.id} className="card p-4"><MobileDataCard title={row.client.name} subtitle={`${date} · Previous ${money(row.previous)}`} amount={money(row.remaining)} status={<Badge tone={row.remaining>0?"red":"green"}>{row.remaining>0?"Due":"Settled"}</Badge>}/><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><Info label="Purchase" value={money(row.purchase)}/><Info label="Paid" value={money(row.paid)}/></div><div className="mt-3"><Payment row={row} value={payments[row.client.id]||""} setValue={v=>setPayments(x=>({...x,[row.client.id]:v}))} full={()=>setPayments(x=>({...x,[row.client.id]:String(Math.max(row.remaining,0))}))} add={()=>pay(row)} loading={add.isPending&&add.variables?.client===row.client.id}/></div></div>)}</div></section>
 </div>
}
function Payment({row,value,setValue,full,add,loading}:{row:DailyRow;value:string;setValue:(v:string)=>void;full:()=>void;add:()=>void;loading:boolean}){return <div className="flex min-w-[250px] gap-2"><div className="relative flex-1"><span className="absolute start-3 top-1/2 -translate-y-1/2 text-xs text-[var(--text-muted)]">Rs</span><input aria-label={`Payment for ${row.client.name}`} min="0" max={Math.max(row.remaining,0)} step="0.01" type="number" className="field h-9 ps-9" value={value} onChange={e=>setValue(e.target.value)} placeholder="0"/></div><button type="button" className="btn-secondary h-9 px-3 text-xs" disabled={row.remaining<=0} onClick={full}>Full</button><button type="button" className="btn-primary h-9 px-3 text-xs" disabled={row.remaining<=0||loading} onClick={add}>{loading?<Loader2 className="size-4 animate-spin"/>:"Add"}</button></div>}
function Summary({label,value,tone}:{label:string;value:string;tone:"primary"|"danger"|"info"|"success"}){const colors={primary:"text-[var(--primary)]",danger:"text-[var(--danger)]",info:"text-[var(--info)]",success:"text-[var(--success)]"};return <div className="border-e p-3 last:border-e-0 sm:px-4"><p className="text-[10px] font-semibold uppercase tracking-wide text-[var(--text-muted)]">{label}</p><p className={`mt-1 text-base font-bold tabular-nums ${colors[tone]}`}>{value}</p></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-[var(--surface-secondary)] p-2"><span className="text-[var(--text-muted)]">{label}</span><b className="mt-1 block">{value}</b></div>}
