import {useEffect,useMemo,useState} from "react";import {useMutation,useQueryClient} from "@tanstack/react-query";import {Boxes,CalendarDays,Check,ChevronDown,ChevronRight,FileText,Loader2,Plus,Printer,ShoppingBasket,Trash2,TriangleAlert,WalletCards} from "lucide-react";
import api,{errorMessage} from "../api";import {useClients,useInventory,usePurchases} from "../hooks";import {InventoryItem,money,PurchaseItem} from "../types";import {Badge,DateNavigator,EmptyState,ErrorState,MobileDataCard,ModuleHeader,SearchInput,StatCard} from "../components/ui";import {toast} from "../components/Toast";
const empty=():PurchaseItem=>({inventory_item:null,item_name:"",unit:"kg",rate:"",quantity:""});
export default function Purchases(){
 const qc=useQueryClient(),clientsQ=useClients(),inventoryQ=useInventory(),q=usePurchases(),clients=clientsQ.data||[],inventory=inventoryQ.data||[],data=q.data||[];
 const [search,setSearch]=useState(""),[historyScope,setHistoryScope]=useState<"date"|"all">("date"),[expanded,setExpanded]=useState<number|null>(null);const [f,setF]=useState({client:"",purchase_date:new Date().toISOString().slice(0,10),reference_number:"",vehicle_number:"",status:"completed",notes:"",items:[empty()]});
 const subtotal=f.items.reduce((s,x)=>s+Number(x.rate)*Number(x.quantity),0),dirty=!!f.client||f.items.some(x=>x.item_name||x.quantity||x.rate);
 const dateMetrics=useMemo(()=>{
  const completed=data.filter(x=>x.status==="completed"),onDate=completed.filter(x=>x.purchase_date===f.purchase_date);
  const soldAfter=new Map<number,number>(),soldOnDate=new Map<number,number>();
  completed.forEach(p=>p.items.forEach(line=>{const id=Number(line.inventory_item);if(!id)return;if(p.purchase_date>f.purchase_date)soldAfter.set(id,(soldAfter.get(id)||0)+Number(line.quantity));if(p.purchase_date===f.purchase_date)soldOnDate.set(id,(soldOnDate.get(id)||0)+Number(line.quantity))}));
  let closingInventory=0,openingInventory=0;
  inventory.forEach(item=>{const rate=Number(item.purchase_rate),closingStock=Number(item.current_stock)+(soldAfter.get(item.id)||0);closingInventory+=closingStock*rate;openingInventory+=(closingStock+(soldOnDate.get(item.id)||0))*rate});
  return {purchaseValue:onDate.reduce((sum,p)=>sum+Number(p.grand_total),0),openingInventory,closingInventory};
 },[data,inventory,f.purchase_date]);
 const historyData=useMemo(()=>{
  const groups=new Map<number,{clientId:number;clientName:string;purchases:typeof data;total:number;latestDate:string}>();
  data.filter(x=>(historyScope==="all"||x.purchase_date===f.purchase_date)&&x.client_name.toLowerCase().includes(search.toLowerCase())).forEach(p=>{
   const group=groups.get(p.client)||{clientId:p.client,clientName:p.client_name,purchases:[],total:0,latestDate:p.purchase_date};
   group.purchases.push(p);group.total+=Number(p.grand_total);if(p.purchase_date>group.latestDate)group.latestDate=p.purchase_date;groups.set(p.client,group);
  });
  return [...groups.values()].sort((a,b)=>b.latestDate.localeCompare(a.latestDate)||b.total-a.total);
 },[data,historyScope,f.purchase_date,search]);
 const historyTotal=historyData.reduce((sum,x)=>sum+x.total,0);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};addEventListener("beforeunload",warn);return()=>removeEventListener("beforeunload",warn)},[dirty]);
 const save=useMutation({mutationFn:()=>api.post("/purchases/",f),onSuccess:()=>{void qc.invalidateQueries({queryKey:["purchases"]});void qc.invalidateQueries({queryKey:["inventory"]});void qc.invalidateQueries({queryKey:["ledger"]});setF({...f,client:"",reference_number:"",vehicle_number:"",notes:"",items:[empty()]});toast("Purchase completed")},onError:e=>toast(errorMessage(e),"error")});
 const update=(i:number,changes:Partial<PurchaseItem>)=>setF({...f,items:f.items.map((x,n)=>n===i?{...x,...changes}:x)});
 const product=(i:number,name:string)=>{const match=inventory.find(x=>x.name.toLocaleLowerCase()===name.trim().toLocaleLowerCase());update(i,{item_name:name,inventory_item:match?.id||null,...(match?{unit:match.unit,rate:match.purchase_rate}:{})})};
 const stockIssues=f.items.map((x,index)=>{const item=inventory.find(y=>y.id===Number(x.inventory_item));return item&&Number(x.quantity)>Number(item.current_stock)?{index,item}:null}).filter((x):x is {index:number;item:InventoryItem}=>x!==null);
 const valid=!!f.client&&f.items.every(x=>x.item_name.trim()&&Number(x.rate)>0&&Number(x.quantity)>0)&&stockIssues.length===0;if(q.isError)return <ErrorState message={errorMessage(q.error)} onRetry={()=>void q.refetch()}/>;
 return <div className="space-y-4"><ModuleHeader title="Sorting / Purchase" description="Record buyer purchases using client accounts and update inventory automatically." icon={ShoppingBasket}><div className="flex flex-col gap-2 sm:flex-row sm:items-end"><div className="min-w-[250px] text-start"><span className="mb-1 block text-[10px] font-semibold uppercase tracking-wide text-emerald-100">Purchase date</span><DateNavigator required value={f.purchase_date} onChange={purchase_date=>setF({...f,purchase_date})} label="Purchase date" className="bg-white !text-slate-900 [color-scheme:light] [&_button]:!text-slate-700 [&_input]:!text-slate-900"/></div><button className="btn h-[42px] border border-white/20 bg-white text-[var(--primary)]" onClick={()=>window.print()}><Printer/>Print</button></div></ModuleHeader>
  <div className="metric-grid grid gap-3 sm:grid-cols-3"><StatCard title="Purchase value on date" value={money(dateMetrics.purchaseValue)} icon={FileText}/><StatCard title="Opening inventory value" value={money(dateMetrics.openingInventory)} icon={Boxes}/><StatCard title="Remaining inventory value" value={money(dateMetrics.closingInventory)} icon={WalletCards}/></div>
  <form onSubmit={e=>{e.preventDefault();save.mutate()}} className="space-y-4"><section className="card p-4"><h2 className="mb-4 text-sm font-bold">Buyer purchase information</h2><div className="max-w-xl"><Field label="Buyer / client"><select required className="field" value={f.client} onChange={e=>setF({...f,client:e.target.value})}><option value="">Select buyer from clients</option>{clients.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field></div></section>
   <section className="card p-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-sm font-bold">Products</h2><p className="text-[11px] text-[var(--text-muted)]">Choose an inventory product or type a new product name.</p></div><button type="button" className="btn-secondary h-9 px-3" onClick={()=>setF({...f,items:[...f.items,empty()]})}><Plus/>Add row</button></div><div className="grid gap-3">{f.items.map((x,i)=><ProductRow key={i} item={x} index={i} inventory={inventory} canRemove={f.items.length>1} onProduct={name=>product(i,name)} onUpdate={changes=>update(i,changes)} onRemove={()=>setF({...f,items:f.items.filter((_,n)=>n!==i)})}/>)}</div></section>
   <section className="card grid gap-4 p-4 md:grid-cols-[1fr_320px]"><Field label="Notes"><textarea className="field min-h-24 p-3" value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></Field><div className={`rounded-[10px] p-4 ${stockIssues.length?"border border-[var(--danger)] bg-[var(--danger-soft)]":"bg-[var(--primary-soft)]"}`}><p className="text-xs text-[var(--text-secondary)]">Grand total</p><p className={`mt-2 text-2xl font-bold ${stockIssues.length?"text-[var(--danger)]":"text-[var(--primary)]"}`}>{money(subtotal)}</p>{stockIssues.length>0&&<div className="mt-3 rounded-lg bg-white/70 p-3 text-xs font-medium text-[var(--danger)]"><TriangleAlert className="mb-1 size-4"/>Reduce the highlighted quantity to the available stock range before completing.</div>}<button className="btn-primary mt-4 w-full" disabled={!valid||save.isPending}>{save.isPending?<Loader2 className="size-4 animate-spin"/>:"Complete purchase"}</button></div></section></form>
  <section className="overflow-hidden rounded-[14px] border bg-[var(--surface)] shadow-[var(--shadow-sm)]">
   <div className="bg-gradient-to-r from-emerald-950 to-emerald-800 p-4 text-white md:flex md:items-center md:justify-between">
    <div><div className="flex items-center gap-2"><span className="grid size-9 place-items-center rounded-xl bg-white/10"><CalendarDays className="size-5"/></span><div><h2 className="font-bold">Purchase activity</h2><p className="text-xs text-emerald-100">Explore buyer transactions and products sold.</p></div></div></div>
    <div className="mt-3 flex gap-2 md:mt-0"><button type="button" onClick={()=>setHistoryScope("date")} className={`rounded-lg px-3 py-2 text-xs font-semibold transition ${historyScope==="date"?"bg-white text-emerald-900 shadow":"bg-white/10 hover:bg-white/20"}`}>Selected date</button><button type="button" onClick={()=>setHistoryScope("all")} className={`rounded-lg px-3 py-2 text-xs font-semibold transition ${historyScope==="all"?"bg-white text-emerald-900 shadow":"bg-white/10 hover:bg-white/20"}`}>All history</button></div>
   </div>
   <div className="grid gap-3 border-b bg-[var(--surface-secondary)] p-3 md:grid-cols-[1fr_auto_auto] md:items-center"><SearchInput value={search} onChange={setSearch} placeholder="Find a buyer..."/><div className="rounded-lg border bg-white px-4 py-2 text-xs"><span className="text-[var(--text-muted)]">Buyers</span><b className="ms-2 text-sm">{historyData.length}</b></div><div className="rounded-lg border bg-white px-4 py-2 text-xs"><span className="text-[var(--text-muted)]">Total value</span><b className="ms-2 text-sm text-[var(--primary)]">{money(historyTotal)}</b></div></div>
   <div className="divide-y">{historyData.length?historyData.map((x,index)=>{const open=expanded===x.clientId,initials=x.clientName.split(" ").slice(0,2).map(part=>part[0]).join("").toUpperCase(),items=x.purchases.flatMap(p=>p.items.map(item=>({...item,purchaseDate:p.purchase_date}))),allCompleted=x.purchases.every(p=>p.status==="completed");return <article key={x.clientId} className="transition hover:bg-emerald-50/40"><button type="button" className="grid w-full grid-cols-[auto_1fr_auto] items-center gap-3 p-4 text-start md:grid-cols-[105px_1fr_170px_120px_auto]" onClick={()=>setExpanded(open?null:x.clientId)}><div className="hidden text-xs text-[var(--text-muted)] md:block"><b className="block text-sm text-[var(--text)]">{new Date(`${x.latestDate}T00:00:00`).toLocaleDateString("en-PK",{day:"2-digit",month:"short"})}</b>{new Date(`${x.latestDate}T00:00:00`).getFullYear()}</div><div className="flex min-w-0 items-center gap-3"><span className={`grid size-10 shrink-0 place-items-center rounded-xl text-xs font-bold ${index%3===0?"bg-emerald-100 text-emerald-700":index%3===1?"bg-blue-100 text-blue-700":"bg-violet-100 text-violet-700"}`}>{initials}</span><div className="min-w-0"><b className="block truncate text-sm">{x.clientName}</b><small className="text-[var(--text-muted)]">{x.purchases.length} transaction{x.purchases.length===1?"":"s"} · {items.length} product{items.length===1?"":"s"}</small></div></div><div className="hidden text-end md:block"><small className="block text-[var(--text-muted)]">Combined value</small><b className="text-base text-[var(--primary)]">{money(x.total)}</b></div><div className="hidden md:block"><Badge tone={allCompleted?"green":"amber"}>{allCompleted?"Completed":"Mixed"}</Badge></div><div className="flex items-center gap-2"><b className="whitespace-nowrap text-[var(--primary)] md:hidden">{money(x.total)}</b><span className={`grid size-8 place-items-center rounded-full bg-[var(--surface-secondary)] transition ${open?"rotate-90 bg-emerald-100 text-emerald-700":""}`}><ChevronRight className="size-4"/></span></div></button>{open&&<div className="border-t bg-[var(--surface-secondary)] px-4 py-3 md:ps-[138px]"><p className="mb-2 text-[10px] font-bold uppercase tracking-wider text-[var(--text-muted)]">Complete purchase details</p><div className="flex flex-wrap gap-2">{items.map((item,i)=><span key={i} className="rounded-lg border bg-white px-3 py-2 text-xs shadow-sm"><b>{item.item_name}</b><span className="ms-2 text-[var(--text-muted)]">{item.quantity} {item.unit} × {money(item.rate)} · {item.purchaseDate}</span></span>)}</div></div>}</article>}):<EmptyState title="No purchase activity found" description={historyScope==="date"?"No purchases were recorded on the selected date.":"Try a different buyer name."}/>}</div>
  </section>
 </div>
}
function ProductInput({value,inventory,onChange}:{index:number;value:string;inventory:InventoryItem[];onChange:(value:string)=>void}){const [open,setOpen]=useState(false),filtered=inventory.filter(x=>x.name.toLowerCase().includes(value.toLowerCase()));return <div className="relative"><div className="relative"><input required role="combobox" aria-expanded={open} className="field pe-10" placeholder="Select or type product name" value={value} onFocus={()=>setOpen(true)} onClick={()=>setOpen(true)} onChange={e=>{onChange(e.target.value);setOpen(true)}} onBlur={()=>setTimeout(()=>setOpen(false),150)} autoComplete="off"/><button aria-label="Open product list" type="button" className="absolute end-0 top-0 grid size-[42px] place-items-center text-[var(--text-muted)]" onMouseDown={e=>e.preventDefault()} onClick={()=>setOpen(x=>!x)}><ChevronDown className={`size-4 transition-transform ${open?"rotate-180":""}`}/></button></div>{open&&<div role="listbox" className="absolute inset-x-0 top-[46px] z-30 max-h-64 overflow-y-auto rounded-[10px] border bg-[var(--surface)] p-1.5 shadow-[0_12px_30px_rgba(15,35,25,.12)]">{filtered.length?filtered.map(x=><button role="option" aria-selected={value===x.name} key={x.id} type="button" className="flex min-h-11 w-full items-center gap-3 rounded-lg px-3 text-start hover:bg-[var(--primary-soft)]" onMouseDown={e=>e.preventDefault()} onClick={()=>{onChange(x.name);setOpen(false)}}><span className="min-w-0 flex-1"><b className="block truncate text-sm">{x.name}</b><small className="block truncate text-[11px] text-[var(--text-muted)]">{x.current_stock} {x.unit} available · {money(x.purchase_rate)}</small></span>{value===x.name&&<Check className="size-4 text-[var(--primary)]"/>}</button>):<div className="p-3 text-center text-xs text-[var(--text-muted)]">No inventory match. Continue typing to use a custom product.</div>}</div>}</div>}
function ProductRow({item,index,inventory,canRemove,onProduct,onUpdate,onRemove}:{item:PurchaseItem;index:number;inventory:InventoryItem[];canRemove:boolean;onProduct:(name:string)=>void;onUpdate:(changes:Partial<PurchaseItem>)=>void;onRemove:()=>void}){const selected=inventory.find(x=>x.id===Number(item.inventory_item)),available=Number(selected?.current_stock||0),over=!!selected&&Number(item.quantity)>available;return <div className={`grid gap-2 rounded-[10px] border p-3 md:grid-cols-[2fr_1fr_1fr_1fr_1fr_auto] ${over?"border-[var(--danger)] bg-[var(--danger-soft)]":"bg-[var(--surface-secondary)]"}`}><Field label="Product"><ProductInput index={index} value={item.item_name} inventory={inventory.filter(x=>x.is_active)} onChange={onProduct}/>{selected&&<p className={`mt-1.5 text-[11px] font-medium ${over?"text-[var(--danger)]":"text-[var(--success)]"}`}>Available: {selected.current_stock} {selected.unit}</p>}</Field><Field label="Quantity"><input required min="0.01" max={selected?.current_stock} step="0.01" type="number" className={`field ${over?"!border-[var(--danger)] !bg-white !text-[var(--danger)] ring-2 ring-red-100":""}`} value={item.quantity} onChange={e=>onUpdate({quantity:e.target.value})}/>{over&&<p className="mt-1.5 text-[11px] font-semibold text-[var(--danger)]">Use a value from 0.01 to {selected.current_stock} {selected.unit}.</p>}</Field><Field label="Unit"><select className="field" value={item.unit} onChange={e=>onUpdate({unit:e.target.value})}><option>kg</option><option>crate</option><option>bag</option><option>piece</option></select></Field><Field label="Rate (PKR)"><input required min="0.01" step="0.01" type="number" className="field" value={item.rate} onChange={e=>onUpdate({rate:e.target.value})}/></Field><div><span className="label">Line total</span><div className={`flex h-[42px] items-center font-bold tabular-nums ${over?"text-[var(--danger)]":""}`}>{money(Number(item.rate)*Number(item.quantity))}</div></div><button aria-label="Remove row" type="button" className="btn-ghost self-end text-[var(--danger)]" disabled={!canRemove} onClick={onRemove}><Trash2/></button></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="label">{label}</span>{children}</label>}
