import {useEffect,useState} from "react";import {useMutation,useQueryClient} from "@tanstack/react-query";import {Check,ChevronDown,FileText,Loader2,Plus,Printer,ShoppingBasket,Trash2,TriangleAlert} from "lucide-react";
import api,{errorMessage} from "../api";import {useClients,useInventory,usePurchases} from "../hooks";import {InventoryItem,money,PurchaseItem} from "../types";import {Badge,EmptyState,ErrorState,MobileDataCard,PageHeader,SearchInput,StatCard} from "../components/ui";import {toast} from "../components/Toast";
const empty=():PurchaseItem=>({inventory_item:null,item_name:"",unit:"kg",rate:"",quantity:""});
export default function Purchases(){
 const qc=useQueryClient(),clientsQ=useClients(),inventoryQ=useInventory(),q=usePurchases(),clients=clientsQ.data||[],inventory=inventoryQ.data||[],data=q.data||[];
 const [search,setSearch]=useState("");const [f,setF]=useState({client:"",purchase_date:new Date().toISOString().slice(0,10),reference_number:"",vehicle_number:"",status:"completed",notes:"",items:[empty()]});
 const subtotal=f.items.reduce((s,x)=>s+Number(x.rate)*Number(x.quantity),0),dirty=!!f.client||f.items.some(x=>x.item_name||x.quantity||x.rate);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};addEventListener("beforeunload",warn);return()=>removeEventListener("beforeunload",warn)},[dirty]);
 const save=useMutation({mutationFn:()=>api.post("/purchases/",f),onSuccess:()=>{void qc.invalidateQueries({queryKey:["purchases"]});void qc.invalidateQueries({queryKey:["inventory"]});void qc.invalidateQueries({queryKey:["ledger"]});setF({...f,client:"",reference_number:"",vehicle_number:"",notes:"",items:[empty()]});toast("Purchase completed")},onError:e=>toast(errorMessage(e),"error")});
 const update=(i:number,changes:Partial<PurchaseItem>)=>setF({...f,items:f.items.map((x,n)=>n===i?{...x,...changes}:x)});
 const product=(i:number,name:string)=>{const match=inventory.find(x=>x.name.toLocaleLowerCase()===name.trim().toLocaleLowerCase());update(i,{item_name:name,inventory_item:match?.id||null,...(match?{unit:match.unit,rate:match.purchase_rate}:{})})};
 const stockIssues=f.items.map((x,index)=>{const item=inventory.find(y=>y.id===Number(x.inventory_item));return item&&Number(x.quantity)>Number(item.current_stock)?{index,item}:null}).filter((x):x is {index:number;item:InventoryItem}=>x!==null);
 const valid=!!f.client&&f.items.every(x=>x.item_name.trim()&&Number(x.rate)>0&&Number(x.quantity)>0)&&stockIssues.length===0;if(q.isError)return <ErrorState message={errorMessage(q.error)} onRetry={()=>void q.refetch()}/>;
 return <div className="space-y-4"><PageHeader title="Sorting / Purchase" description="Record buyer purchases using client accounts and update inventory automatically."><button className="btn-secondary" onClick={()=>window.print()}><Printer/>Print</button></PageHeader>
  <div className="metric-grid grid gap-3 sm:grid-cols-3"><StatCard title="Today's lots" value={data.filter(x=>x.purchase_date===f.purchase_date).length} icon={ShoppingBasket}/><StatCard title="Purchase value" value={money(data.reduce((s,x)=>s+Number(x.grand_total),0))} icon={FileText}/><StatCard title="Completed" value={data.filter(x=>x.status==="completed").length} icon={ShoppingBasket}/></div>
  <form onSubmit={e=>{e.preventDefault();save.mutate()}} className="space-y-4"><section className="card p-4"><h2 className="mb-4 text-sm font-bold">Buyer purchase information</h2><div className="grid gap-3 md:grid-cols-4"><Field label="Buyer / client"><select required className="field" value={f.client} onChange={e=>setF({...f,client:e.target.value})}><option value="">Select buyer from clients</option>{clients.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Purchase date"><input required className="field" type="date" value={f.purchase_date} onChange={e=>setF({...f,purchase_date:e.target.value})}/></Field><Field label="Vehicle number"><input className="field" value={f.vehicle_number} onChange={e=>setF({...f,vehicle_number:e.target.value})}/></Field><Field label="Reference number"><input className="field" value={f.reference_number} onChange={e=>setF({...f,reference_number:e.target.value})}/></Field></div></section>
   <section className="card p-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-sm font-bold">Products</h2><p className="text-[11px] text-[var(--text-muted)]">Choose an inventory product or type a new product name.</p></div><button type="button" className="btn-secondary h-9 px-3" onClick={()=>setF({...f,items:[...f.items,empty()]})}><Plus/>Add row</button></div><div className="grid gap-3">{f.items.map((x,i)=><ProductRow key={i} item={x} index={i} inventory={inventory} canRemove={f.items.length>1} onProduct={name=>product(i,name)} onUpdate={changes=>update(i,changes)} onRemove={()=>setF({...f,items:f.items.filter((_,n)=>n!==i)})}/>)}</div></section>
   <section className="card grid gap-4 p-4 md:grid-cols-[1fr_320px]"><Field label="Notes"><textarea className="field min-h-24 p-3" value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></Field><div className={`rounded-[10px] p-4 ${stockIssues.length?"border border-[var(--danger)] bg-[var(--danger-soft)]":"bg-[var(--primary-soft)]"}`}><p className="text-xs text-[var(--text-secondary)]">Grand total</p><p className={`mt-2 text-2xl font-bold ${stockIssues.length?"text-[var(--danger)]":"text-[var(--primary)]"}`}>{money(subtotal)}</p>{stockIssues.length>0&&<div className="mt-3 rounded-lg bg-white/70 p-3 text-xs font-medium text-[var(--danger)]"><TriangleAlert className="mb-1 size-4"/>Reduce the highlighted quantity to the available stock range before completing.</div>}<button className="btn-primary mt-4 w-full" disabled={!valid||save.isPending}>{save.isPending?<Loader2 className="size-4 animate-spin"/>:"Complete purchase"}</button></div></section></form>
  <section className="table-wrap"><div className="border-b p-3"><SearchInput value={search} onChange={setSearch} placeholder="Search buyer purchase history..."/></div><div className="desktop-table overflow-x-auto">{data.length?<table className="data-table"><thead><tr><th>Date</th><th>Reference</th><th>Buyer / Client</th><th>Vehicle</th><th className="numeric">Total</th><th>Status</th></tr></thead><tbody>{data.filter(x=>(x.client_name+x.reference_number).toLowerCase().includes(search.toLowerCase())).map(x=><tr key={x.id}><td>{x.purchase_date}</td><td>{x.reference_number||`#${x.id}`}</td><td className="font-semibold">{x.client_name}</td><td>{x.vehicle_number||"—"}</td><td className="numeric font-semibold">{money(x.grand_total)}</td><td><Badge tone={x.status==="completed"?"green":"amber"}>{x.status}</Badge></td></tr>)}</tbody></table>:<EmptyState/>}</div><div className="mobile-cards gap-2 p-3">{data.map(x=><MobileDataCard key={x.id} title={x.client_name} subtitle={`${x.purchase_date} · ${x.reference_number||`#${x.id}`}`} amount={money(x.grand_total)} status={<Badge tone={x.status==="completed"?"green":"amber"}>{x.status}</Badge>}/>)}</div></section>
 </div>
}
function ProductInput({value,inventory,onChange}:{index:number;value:string;inventory:InventoryItem[];onChange:(value:string)=>void}){const [open,setOpen]=useState(false),filtered=inventory.filter(x=>x.name.toLowerCase().includes(value.toLowerCase()));return <div className="relative"><div className="relative"><input required role="combobox" aria-expanded={open} className="field pe-10" placeholder="Select or type product name" value={value} onFocus={()=>setOpen(true)} onClick={()=>setOpen(true)} onChange={e=>{onChange(e.target.value);setOpen(true)}} onBlur={()=>setTimeout(()=>setOpen(false),150)} autoComplete="off"/><button aria-label="Open product list" type="button" className="absolute end-0 top-0 grid size-[42px] place-items-center text-[var(--text-muted)]" onMouseDown={e=>e.preventDefault()} onClick={()=>setOpen(x=>!x)}><ChevronDown className={`size-4 transition-transform ${open?"rotate-180":""}`}/></button></div>{open&&<div role="listbox" className="absolute inset-x-0 top-[46px] z-30 max-h-64 overflow-y-auto rounded-[10px] border bg-[var(--surface)] p-1.5 shadow-[0_12px_30px_rgba(15,35,25,.12)]">{filtered.length?filtered.map(x=><button role="option" aria-selected={value===x.name} key={x.id} type="button" className="flex min-h-11 w-full items-center gap-3 rounded-lg px-3 text-start hover:bg-[var(--primary-soft)]" onMouseDown={e=>e.preventDefault()} onClick={()=>{onChange(x.name);setOpen(false)}}><span className="min-w-0 flex-1"><b className="block truncate text-sm">{x.name}</b><small className="block truncate text-[11px] text-[var(--text-muted)]">{x.current_stock} {x.unit} available · {money(x.purchase_rate)}</small></span>{value===x.name&&<Check className="size-4 text-[var(--primary)]"/>}</button>):<div className="p-3 text-center text-xs text-[var(--text-muted)]">No inventory match. Continue typing to use a custom product.</div>}</div>}</div>}
function ProductRow({item,index,inventory,canRemove,onProduct,onUpdate,onRemove}:{item:PurchaseItem;index:number;inventory:InventoryItem[];canRemove:boolean;onProduct:(name:string)=>void;onUpdate:(changes:Partial<PurchaseItem>)=>void;onRemove:()=>void}){const selected=inventory.find(x=>x.id===Number(item.inventory_item)),available=Number(selected?.current_stock||0),over=!!selected&&Number(item.quantity)>available;return <div className={`grid gap-2 rounded-[10px] border p-3 md:grid-cols-[2fr_1fr_1fr_1fr_1fr_auto] ${over?"border-[var(--danger)] bg-[var(--danger-soft)]":"bg-[var(--surface-secondary)]"}`}><Field label="Product"><ProductInput index={index} value={item.item_name} inventory={inventory.filter(x=>x.is_active)} onChange={onProduct}/>{selected&&<p className={`mt-1.5 text-[11px] font-medium ${over?"text-[var(--danger)]":"text-[var(--success)]"}`}>Available: {selected.current_stock} {selected.unit}</p>}</Field><Field label="Quantity"><input required min="0.01" max={selected?.current_stock} step="0.01" type="number" className={`field ${over?"!border-[var(--danger)] !bg-white !text-[var(--danger)] ring-2 ring-red-100":""}`} value={item.quantity} onChange={e=>onUpdate({quantity:e.target.value})}/>{over&&<p className="mt-1.5 text-[11px] font-semibold text-[var(--danger)]">Use a value from 0.01 to {selected.current_stock} {selected.unit}.</p>}</Field><Field label="Unit"><select className="field" value={item.unit} onChange={e=>onUpdate({unit:e.target.value})}><option>kg</option><option>crate</option><option>bag</option><option>piece</option></select></Field><Field label="Rate (PKR)"><input required min="0.01" step="0.01" type="number" className="field" value={item.rate} onChange={e=>onUpdate({rate:e.target.value})}/></Field><div><span className="label">Line total</span><div className={`flex h-[42px] items-center font-bold tabular-nums ${over?"text-[var(--danger)]":""}`}>{money(Number(item.rate)*Number(item.quantity))}</div></div><button aria-label="Remove row" type="button" className="btn-ghost self-end text-[var(--danger)]" disabled={!canRemove} onClick={onRemove}><Trash2/></button></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="label">{label}</span>{children}</label>}
