import {useEffect,useMemo,useRef,useState} from "react";
import {useMutation,useQueryClient} from "@tanstack/react-query";
import {useNavigate} from "react-router-dom";
import {Banknote,Download,Loader2,MapPin,MoreVertical,Pencil,Phone,Plus,Search,ShoppingBasket,Store,Trash2,Upload,UsersRound,X} from "lucide-react";
import api,{errorMessage} from "../api";
import {useVendors} from "../hooks";
import {money,Vendor} from "../types";
import {Badge,ConfirmDialog,EmptyState,ErrorState,FormModal,Pagination} from "../components/ui";
import {toast} from "../components/Toast";
import {VendorHeader} from "../components/VendorHeader";
import {useVendorUrdu} from "../vendorUrdu";

const vendorBlank={name:"",name_ur:"",phone:"",address:"",city:"",category:"Retailer",credit_limit:"0",opening_balance:"0",notes:"",is_active:true};
const palette=["bg-emerald-100 text-emerald-700","bg-blue-100 text-blue-700","bg-amber-100 text-amber-700","bg-violet-100 text-violet-700","bg-cyan-100 text-cyan-700","bg-rose-100 text-rose-700"];
const csvCell=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;

export default function Vendors(){
 const nav=useNavigate(),qc=useQueryClient(),vendorsQ=useVendors(),vendors=vendorsQ.data||[],fileRef=useRef<HTMLInputElement>(null);
 const pageRef=useRef<HTMLDivElement>(null);useVendorUrdu(pageRef);
 const [search,setSearch]=useState(""),[status,setStatus]=useState("all"),[city,setCity]=useState("all"),[category,setCategory]=useState("all"),[page,setPage]=useState(1);
 const [vendorModal,setVendorModal]=useState(false),[editing,setEditing]=useState<Vendor|null>(null),[deleting,setDeleting]=useState<Vendor|null>(null),[actionMenu,setActionMenu]=useState<number|null>(null);
 const [vendorForm,setVendorForm]=useState(vendorBlank);
 useEffect(()=>{if(actionMenu===null)return;const close=()=>setActionMenu(null);document.addEventListener("click",close);return()=>document.removeEventListener("click",close)},[actionMenu]);
 const cities=useMemo(()=>[...new Set(vendors.map(v=>v.city).filter(Boolean))].sort(),[vendors]);
 const categories=useMemo(()=>[...new Set(vendors.map(v=>v.category).filter(Boolean))].sort(),[vendors]);
 const filtered=useMemo(()=>vendors.filter(v=>{
  const query=`${v.name} ${v.name_ur||""} ${v.phone||""} ${v.address||""} ${v.city||""}`.toLowerCase();
  return query.includes(search.toLowerCase())&&(status==="all"||(status==="active")===v.is_active)&&(city==="all"||v.city===city)&&(category==="all"||v.category===category);
 }),[vendors,search,status,city,category]);
 const pageSize=10,paged=filtered.slice((page-1)*pageSize,page*pageSize);
 const refresh=()=>qc.invalidateQueries({queryKey:["vendors"]});
 const saveVendor=useMutation({mutationFn:()=>editing?api.patch(`/vendors/${editing.id}/`,vendorForm):api.post("/vendors/",vendorForm),onSuccess:async()=>{await refresh();setVendorModal(false);setEditing(null);setVendorForm(vendorBlank);toast(editing?"Vendor updated":"Vendor added")},onError:e=>toast(errorMessage(e),"error")});
 const deleteVendor=useMutation({mutationFn:(id:number)=>api.delete(`/vendors/${id}/`),onSuccess:async()=>{await refresh();setDeleting(null);toast("Vendor deleted")},onError:e=>toast(errorMessage(e),"error")});
 const openVendorForm=(vendor?:Vendor)=>{setEditing(vendor||null);setVendorForm(vendor?{name:vendor.name,name_ur:vendor.name_ur||"",phone:vendor.phone||"",address:vendor.address||"",city:vendor.city||"",category:vendor.category||"Retailer",credit_limit:vendor.credit_limit||"0",opening_balance:vendor.opening_balance,notes:vendor.notes||"",is_active:vendor.is_active}:vendorBlank);setVendorModal(true)};
 const clearFilters=()=>{setSearch("");setStatus("all");setCity("all");setCategory("all");setPage(1)};
 const exportCsv=()=>{const rows=[["Vendor ID","Name","Phone","Address","City","Category","Credit Limit","Payable","Status","Joined"],...filtered.map(v=>[`VND-${String(v.id).padStart(3,"0")}`,v.name,v.phone,v.address,v.city,v.category,v.credit_limit,v.balance,v.is_active?"Active":"Inactive",v.created_at?.slice(0,10)||""])];const blob=new Blob([rows.map(r=>r.map(csvCell).join(",")).join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="vendors.csv";a.click();URL.revokeObjectURL(url);toast("Vendor list exported")};
 const importCsv=async(file?:File)=>{if(!file)return;try{const lines=(await file.text()).split(/\r?\n/).filter(Boolean),headers=lines.shift()?.split(",").map(x=>x.replace(/^"|"$/g,"").trim().toLowerCase())||[];let count=0;for(const line of lines){const values=line.match(/(".*?"|[^",]+)(?=\s*,|\s*$)/g)?.map(x=>x.replace(/^"|"$/g,"").replaceAll('""','"'))||[];const row=Object.fromEntries(headers.map((h,i)=>[h,values[i]||""]));if(!row.name)continue;await api.post("/vendors/",{...vendorBlank,name:row.name,phone:row.phone||"",address:row.address||"",city:row.city||"",category:row.category||"Retailer",credit_limit:row["credit limit"]||"0",opening_balance:row["opening balance"]||"0",is_active:(row.status||"active").toLowerCase()!=="inactive"});count++}await refresh();toast(`${count} vendor${count===1?"":"s"} imported`)}catch(e){toast(errorMessage(e),"error")}finally{if(fileRef.current)fileRef.current.value=""}};
 if(vendorsQ.isError)return <ErrorState message={errorMessage(vendorsQ.error)} onRetry={()=>void vendorsQ.refetch()}/>;
 return <div ref={pageRef} className="vendor-page space-y-3">
  <VendorHeader title="Vendors" subtitle="Manage suppliers, purchases, payments and outstanding balances."><button className="flex h-10 items-center gap-2 rounded-xl bg-white px-3 text-xs font-bold text-[var(--sidebar)] hover:bg-green-50" onClick={exportCsv}><Download className="size-4"/>Export</button><button className="flex h-10 items-center gap-2 rounded-xl bg-white px-3 text-xs font-bold text-[var(--sidebar)] hover:bg-green-50" onClick={()=>fileRef.current?.click()}><Upload className="size-4"/>Import</button><input ref={fileRef} type="file" accept=".csv,text/csv" className="hidden" onChange={e=>void importCsv(e.target.files?.[0])}/><button className="flex h-10 items-center gap-2 rounded-xl bg-emerald-500 px-4 text-xs font-bold text-white shadow-sm hover:bg-emerald-400" onClick={()=>openVendorForm()}><Plus className="size-4"/>Add Vendor</button></VendorHeader>
  <div className="grid gap-2.5 sm:grid-cols-2 xl:grid-cols-4">
   <Summary icon={UsersRound} tone="green" label="Total vendors" value={vendors.length} detail={`${vendors.filter(v=>v.is_active).length} active accounts`}/>
   <Summary icon={Store} tone="blue" label="Active accounts" value={vendors.filter(v=>v.is_active).length} detail={`${vendors.filter(v=>!v.is_active).length} inactive`}/>
   <Summary icon={ShoppingBasket} tone="amber" label="Total purchases" value={money(vendors.reduce((sum,v)=>sum+Number(v.total_received),0))} detail="Across all vendors"/>
   <Summary icon={Banknote} tone="red" label="Outstanding payable" value={money(vendors.reduce((sum,v)=>sum+Number(v.balance),0))} detail="Current vendor balance"/>
  </div>
  <section className="vendor-directory card overflow-visible">
   <div className="flex flex-col gap-2 border-b px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-extrabold">Vendor directory</h2><p className="mt-0.5 text-[11px] text-[var(--text-muted)]">Open a vendor to view transactions, payments and monthly history.</p></div><Badge tone="green">{filtered.length} vendors</Badge></div>
   <div className="grid gap-2.5 border-b bg-[var(--surface-secondary)]/50 px-4 py-3 lg:grid-cols-[minmax(260px,1fr)_145px_150px_165px_auto]"><label><span className="label">Search</span><div className="relative"><Search className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-[var(--text-muted)]"/><input className="field ps-9" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Name, phone or city..."/></div></label><Filter label="Status" value={status} onChange={setStatus} options={[["all","All status"],["active","Active"],["inactive","Inactive"]]}/><Filter label="City" value={city} onChange={setCity} options={[["all","All cities"],...cities.map(x=>[x,x])]}/><Filter label="Category" value={category} onChange={setCategory} options={[["all","All categories"],...categories.map(x=>[x,x])]}/><button className="btn-secondary self-end" onClick={clearFilters}><X/>Clear</button></div>
   <div className="desktop-table overflow-x-auto"><table className="data-table min-w-[940px]"><thead><tr><th>Vendor</th><th>Contact & location</th><th>Category</th><th className="numeric">Total purchases</th><th className="numeric">Payable</th><th>Status</th><th>Actions</th></tr></thead><tbody>{paged.map((v,index)=><tr key={v.id} className="cursor-pointer transition-colors hover:bg-[var(--primary-soft)]" onClick={()=>nav(`/vendors/${v.id}`)}><td><div className="flex items-center gap-3"><span className={`grid size-11 shrink-0 place-items-center rounded-xl text-xs font-extrabold ${palette[(v.id+index)%palette.length]}`}>{v.name.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()}</span><span className="min-w-0"><b className="block truncate text-[var(--text-primary)]">{v.name}</b><small className="font-semibold text-[var(--text-muted)]">VND-{String(v.id).padStart(3,"0")}{v.name_ur?` · ${v.name_ur}`:""}</small></span></div></td><td><span className="block whitespace-nowrap"><Phone className="me-1.5 inline size-3.5 text-[var(--text-muted)]"/>{v.phone||"No phone"}</span><small className="mt-1 block text-[var(--text-muted)]"><MapPin className="me-1 inline size-3"/>{v.city||v.address||"No location"}</small></td><td><Badge tone={v.category==="Wholesaler"?"blue":"green"}>{v.category||"Uncategorized"}</Badge></td><td className="numeric font-semibold">{money(v.total_received)}</td><td className={`numeric text-sm font-black ${Number(v.balance)>0?"text-[var(--danger)]":"text-[var(--primary)]"}`}>{money(v.balance)}</td><td><Badge tone={v.is_active?"green":"red"}>{v.is_active?"● Active":"● Inactive"}</Badge></td><td onClick={e=>e.stopPropagation()}><div className="relative shrink-0"><button className="icon-btn size-8" aria-label={`Actions for ${v.name}`} onClick={e=>{e.stopPropagation();setActionMenu(actionMenu===v.id?null:v.id)}}><MoreVertical className="size-4"/></button>{actionMenu===v.id&&<div className="absolute end-0 top-9 z-30 w-44 rounded-xl border bg-[var(--surface)] p-1.5 shadow-xl"><button className="flex h-9 w-full items-center gap-2 rounded-lg px-3 text-xs font-semibold hover:bg-[var(--primary-soft)]" onClick={()=>openVendorForm(v)}><Pencil className="size-4"/>Update vendor</button><button className="flex h-9 w-full items-center gap-2 rounded-lg px-3 text-xs font-semibold text-[var(--danger)] hover:bg-[var(--danger-soft)]" onClick={()=>setDeleting(v)}><Trash2 className="size-4"/>Delete vendor</button></div>}</div></td></tr>)}</tbody></table>{!paged.length&&<EmptyState title="No vendors found" description="Try clearing the filters or add a new vendor."/>}</div>
   <div className="mobile-cards gap-3 p-3">{paged.map((v,index)=><article key={v.id} className="rounded-2xl border bg-[var(--surface)] p-4 shadow-sm" onClick={()=>nav(`/vendors/${v.id}`)}><div className="flex items-start gap-3"><span className={`grid size-11 shrink-0 place-items-center rounded-xl text-xs font-extrabold ${palette[(v.id+index)%palette.length]}`}>{v.name.split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()}</span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><b className="block truncate">{v.name}</b><p className="mt-1 text-xs text-[var(--text-muted)]">{v.phone||"No phone"} · {v.city||"No city"}</p></div><Badge tone={v.is_active?"green":"red"}>{v.is_active?"Active":"Inactive"}</Badge></div></div></div><div className="mt-4 grid grid-cols-2 gap-3 border-t pt-3"><span><small className="text-[var(--text-muted)]">Purchases</small><b className="mt-1 block">{money(v.total_received)}</b></span><span className="text-end"><small className="text-[var(--text-muted)]">Payable</small><b className="mt-1 block text-[var(--danger)]">{money(v.balance)}</b></span></div></article>)}</div>
   <div className="border-t"><Pagination count={filtered.length} page={page} setPage={setPage} pageSize={pageSize}/></div>
  </section>
  <FormModal open={vendorModal} onClose={()=>{setVendorModal(false);setEditing(null)}} title={editing?`Edit ${editing.name}`:"Add new vendor"} description="Create or update the vendor directory and account details." variant="full"><form className="grid gap-4 p-5 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();saveVendor.mutate()}}><Field label="Vendor name"><input required className="field" value={vendorForm.name} onChange={e=>setVendorForm({...vendorForm,name:e.target.value})}/></Field><Field label="Name in Urdu"><input dir="rtl" className="field text-right" value={vendorForm.name_ur} onChange={e=>setVendorForm({...vendorForm,name_ur:e.target.value})}/></Field><Field label="Phone / WhatsApp"><input className="field" value={vendorForm.phone} onChange={e=>setVendorForm({...vendorForm,phone:e.target.value})}/></Field><Field label="City"><input className="field" value={vendorForm.city} onChange={e=>setVendorForm({...vendorForm,city:e.target.value})}/></Field><Field label="Category"><select className="field" value={vendorForm.category} onChange={e=>setVendorForm({...vendorForm,category:e.target.value})}><option>Retailer</option><option>Wholesaler</option><option>Farmer</option><option>Distributor</option><option>Other</option></select></Field><Field label="Credit limit"><input min="0" type="number" className="field" value={vendorForm.credit_limit} onChange={e=>setVendorForm({...vendorForm,credit_limit:e.target.value})}/></Field><Field label="Opening payable"><input min="0" type="number" className="field" value={vendorForm.opening_balance} onChange={e=>setVendorForm({...vendorForm,opening_balance:e.target.value})}/></Field><Field label="Address"><input className="field" value={vendorForm.address} onChange={e=>setVendorForm({...vendorForm,address:e.target.value})}/></Field><Field label="Notes" full><textarea className="field min-h-24 p-3" value={vendorForm.notes} onChange={e=>setVendorForm({...vendorForm,notes:e.target.value})}/></Field><label className="flex items-center gap-2 rounded-xl bg-[var(--surface-secondary)] p-3 text-sm font-semibold"><input type="checkbox" checked={vendorForm.is_active} onChange={e=>setVendorForm({...vendorForm,is_active:e.target.checked})}/>Active vendor account</label><Actions close={()=>{setVendorModal(false);setEditing(null)}} loading={saveVendor.isPending} label={editing?"Update Vendor":"Save Vendor"}/></form></FormModal>
  <ConfirmDialog open={!!deleting} onClose={()=>setDeleting(null)} onConfirm={()=>deleting&&deleteVendor.mutate(deleting.id)} loading={deleteVendor.isPending} title={`Delete ${deleting?.name||"vendor"}?`}/>
 </div>
}
function Summary({icon:Icon,tone,label,value,detail}:{icon:React.ElementType;tone:"green"|"blue"|"amber"|"red";label:string;value:string|number;detail:string}){const colors={green:"bg-emerald-100 text-emerald-700",blue:"bg-blue-100 text-blue-700",amber:"bg-amber-100 text-amber-700",red:"bg-rose-100 text-rose-700"};return <div className={`vendor-summary-card vendor-summary-${tone} card relative flex min-h-20 items-center gap-3 overflow-hidden px-3.5 py-3 before:absolute before:inset-x-0 before:top-0 before:h-0.5 before:bg-current ${tone==="red"?"text-rose-600":tone==="blue"?"text-blue-600":tone==="amber"?"text-amber-600":"text-emerald-600"}`}><span className={`grid size-9 shrink-0 place-items-center rounded-lg ${colors[tone]}`}><Icon className="size-4.5"/></span><span className="min-w-0 text-[var(--text-primary)]"><small className="text-[11px] font-semibold text-[var(--text-muted)]">{label}</small><b className="mt-0.5 block truncate text-lg font-black tabular-nums">{value}</b><small className="mt-0.5 block text-[9px] text-[var(--text-muted)]">{detail}</small></span></div>}
function Filter({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[][]}){return <label><span className="label">{label}</span><select className="field" value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>}
function Field({label,children,full}:{label:string;children:React.ReactNode;full?:boolean}){return <label className={full?"sm:col-span-full":""}><span className="label">{label}</span>{children}</label>}
function Actions({close,loading,label}:{close:()=>void;loading:boolean;label:string}){return <div className="sticky bottom-0 col-span-full flex justify-end gap-2 border-t bg-[var(--surface)] py-3"><button type="button" className="btn-secondary" onClick={close}>Cancel</button><button className="btn-primary" disabled={loading}>{loading?<Loader2 className="animate-spin"/>:label}</button></div>}
