import {useMemo} from "react";
import {useQuery} from "@tanstack/react-query";
import {ArrowLeft,CalendarDays,Loader2} from "lucide-react";
import {Link,useParams} from "react-router-dom";
import api,{errorMessage} from "../api";
import {EmptyState,ErrorState} from "../components/ui";
import {money,unwrap,Vendor,VendorDailyExpense,VendorEntry,VendorPayment} from "../types";
import {VendorHeader} from "../components/VendorHeader";

export default function VendorMonthHistory(){
 const {id,month=""}=useParams(),vendorId=Number(id),validMonth=/^\d{4}-\d{2}$/.test(month);
 const vendorQ=useQuery({queryKey:["vendor",vendorId],queryFn:async()=>(await api.get<Vendor>(`/vendors/${vendorId}/`)).data,enabled:Number.isFinite(vendorId)});
 const entriesQ=useQuery({queryKey:["vendor-entries",vendorId],queryFn:async()=>unwrap<VendorEntry>((await api.get(`/vendor-entries/?vendor=${vendorId}`)).data),enabled:Number.isFinite(vendorId)});
 const paymentsQ=useQuery({queryKey:["vendor-payments",vendorId],queryFn:async()=>unwrap<VendorPayment>((await api.get(`/vendor-payments/?vendor=${vendorId}`)).data),enabled:Number.isFinite(vendorId)});
 const expensesQ=useQuery({queryKey:["vendor-daily-expenses",vendorId],queryFn:async()=>unwrap<VendorDailyExpense>((await api.get(`/vendor-daily-expenses/?vendor=${vendorId}`)).data),enabled:Number.isFinite(vendorId)});
 const rows=useMemo(()=>{const entries=(entriesQ.data||[]).filter(x=>x.entry_date.startsWith(month)),payments=(paymentsQ.data||[]).filter(x=>x.payment_date.startsWith(month)),expenses=(expensesQ.data||[]).filter(x=>x.expense_date.startsWith(month));const dates=new Set([...entries.map(x=>x.entry_date),...payments.map(x=>x.payment_date),...expenses.map(x=>x.expense_date)]);return [...dates].sort((a,b)=>b.localeCompare(a)).map(date=>{const amount=entries.filter(x=>x.entry_date===date).reduce((sum,x)=>sum+Number(x.vendor_amount),0),expense=expenses.find(x=>x.expense_date===date),payment=payments.filter(x=>x.payment_date===date).reduce((sum,x)=>sum+Number(x.amount),0);return {date,finalBalance:expense?Number(expense.final_amount):amount,payment}})},[entriesQ.data,paymentsQ.data,expensesQ.data,month]);
 const previousBalance=useMemo(()=>{const monthStart=`${month}-01`,priorEntries=(entriesQ.data||[]).filter(x=>x.entry_date<monthStart).reduce((sum,x)=>sum+Number(x.vendor_amount),0),priorExpenses=(expensesQ.data||[]).filter(x=>x.expense_date<monthStart).reduce((sum,x)=>sum+Number(x.total_deductions),0),priorPayments=(paymentsQ.data||[]).filter(x=>x.payment_date<monthStart).reduce((sum,x)=>sum+Number(x.amount),0);return Number(vendorQ.data?.opening_balance||0)+priorEntries-priorExpenses-priorPayments},[entriesQ.data,expensesQ.data,paymentsQ.data,vendorQ.data?.opening_balance,month]);
 const previousPayment=useMemo(()=>{const monthStart=`${month}-01`;return (paymentsQ.data||[]).filter(x=>x.payment_date<monthStart).reduce((sum,x)=>sum+Number(x.amount),0)},[paymentsQ.data,month]);
 const previousLastDate=useMemo(()=>{const monthStart=`${month}-01`,dates=[...(entriesQ.data||[]).map(x=>x.entry_date),...(paymentsQ.data||[]).map(x=>x.payment_date),...(expensesQ.data||[]).map(x=>x.expense_date)].filter(date=>date<monthStart).sort();return dates[dates.length-1]||"Previous"},[entriesQ.data,paymentsQ.data,expensesQ.data,month]);
 const monthEntries=rows.reduce((sum,row)=>sum+row.finalBalance,0),totalPayment=rows.reduce((sum,row)=>sum+row.payment,0),allPayments=previousPayment+totalPayment,closingBalance=previousBalance+monthEntries-totalPayment;
 const loading=vendorQ.isLoading||entriesQ.isLoading||paymentsQ.isLoading||expensesQ.isLoading;
 const failed=vendorQ.isError||entriesQ.isError||paymentsQ.isError||expensesQ.isError;
 if(!validMonth)return <ErrorState message="Invalid history month."/>;
 if(failed)return <ErrorState message={errorMessage(vendorQ.error||entriesQ.error||paymentsQ.error||expensesQ.error)}/>;
 if(loading||!vendorQ.data)return <div className="card p-8"><Loader2 className="mx-auto animate-spin text-[var(--primary)]"/></div>;
 const monthLabel=new Date(`${month}-01T12:00:00`).toLocaleDateString("en-PK",{month:"long",year:"numeric"});
 return <div className="space-y-4">
  <VendorHeader title={`${monthLabel} History`} subtitle={`${vendorQ.data.name} · Date-wise monthly history`} backTo={`/vendors/${vendorId}?tab=history`}/>
  <section className="table-wrap">
   <div className="flex items-center gap-3 border-b p-4"><span className="grid size-10 place-items-center rounded-xl bg-[var(--primary-soft)] text-[var(--primary)]"><CalendarDays className="size-5"/></span><div><h2 className="font-bold">{monthLabel}</h2><p className="text-xs text-[var(--text-muted)]">{rows.length} business dates</p></div></div>
   {rows.length?<><div className="desktop-table overflow-x-auto"><table className="data-table"><thead><tr><th>Date</th><th className="numeric">Final balance</th><th className="numeric">Payment</th></tr></thead><tbody><tr className="bg-[var(--danger-soft)]"><td className="font-black text-[var(--danger)]">{previousLastDate}</td><td className="numeric font-black text-[var(--danger)]">{money(previousBalance)}</td><td className="numeric font-black text-[var(--danger)]">{money(previousPayment)}</td></tr>{rows.map(row=><tr key={row.date}><td className="font-semibold">{row.date}</td><td className="numeric font-bold">{money(row.finalBalance)}</td><td className="numeric font-bold text-[var(--danger)]">{row.payment?money(row.payment):"—"}</td></tr>)}</tbody><tfoot><tr className="bg-[var(--surface-secondary)]"><td className="font-black">Closing totals</td><td className="numeric font-black">{money(closingBalance)}</td><td className="numeric font-black text-[var(--danger)]">{money(allPayments)}</td></tr></tfoot></table></div><div className="mobile-cards gap-2 p-3"><div className="rounded-xl border border-red-200 bg-[var(--danger-soft)] p-4"><b className="mb-3 block text-[var(--danger)]">{previousLastDate}</b><div className="grid grid-cols-2 gap-3"><span><small className="font-bold text-[var(--danger)]">Previous balance</small><b className="mt-1 block text-[var(--danger)]">{money(previousBalance)}</b></span><span className="text-end"><small className="font-bold text-[var(--danger)]">Previous payment</small><b className="mt-1 block text-[var(--danger)]">{money(previousPayment)}</b></span></div></div>{rows.map(row=><article className="card p-4" key={row.date}><b>{row.date}</b><div className="mt-3 grid grid-cols-2 gap-3 border-t pt-3"><span><small>Final balance</small><b className="block">{money(row.finalBalance)}</b></span><span className="text-end"><small>Payment</small><b className="block text-[var(--danger)]">{row.payment?money(row.payment):"—"}</b></span></div></article>)}<div className="grid grid-cols-2 gap-3 rounded-xl bg-[var(--surface-secondary)] p-4"><span><small>Closing balance</small><b className="block">{money(closingBalance)}</b></span><span className="text-end"><small>Total payment</small><b className="block text-[var(--danger)]">{money(allPayments)}</b></span></div></div></>:<EmptyState/>}
  </section>
 </div>
}
